//! Embeds the Windows application icon into the `indicatrix-worker` binary.
//!
//! `assets/icon.ico` (emerald, vs. the viewer's cyan) is generated by
//! `scripts/make-icons.py`; Windows also uses an executable's first icon resource for
//! its console window.
//!
//! # This crate deliberately keeps its console
//!
//! No `windows_subsystem = "windows"` here, unlike `indicatrix-cut`: `render`, `serve`
//! and `cert` all print to stdout, and a Windows-subsystem binary would detach it,
//! silencing the CLI entirely.
//!
//! # Failure is a warning, not an error
//!
//! Embedding needs a resource compiler (`rc.exe`/`windres`), not guaranteed present when
//! cross-compiling (see `scripts/pgo-bolt-build.sh`). A missing icon must never fail the
//! build, so this reports and continues.

fn main() {
    #[cfg(windows)]
    embed_icon();
}

#[cfg(windows)]
fn embed_icon() {
    println!("cargo:rerun-if-changed=assets/icon.ico");
    let mut res = winresource::WindowsResource::new();
    res.set_icon("assets/icon.ico");
    if let Err(e) = res.compile() {
        println!(
            "cargo:warning=could not embed the application icon ({e}); the binary will build without one"
        );
    }
}
