//! Compiles the Slint UI, and on Windows embeds the application icon.
//!
//! `assets/icon.ico` is generated by `scripts/make-icons.py` (cyan, against
//! `indicatrix-worker`'s emerald). Embedding it as a resource gives the `.exe` its icon
//! in Explorer. It does NOT reach the windows' titlebar/taskbar icon: winit registers
//! its window class without one, so each Slint `Window` sets `icon` to
//! `assets/icon.png` itself (see `MainWindow` in `ui/app.slint`); Slint embeds that
//! image in the binary, so nothing has to be installed next to it.
//!
//! Embedding needs a resource compiler (`rc.exe` for `msvc`, `windres` for `gnu`),
//! neither guaranteed present, particularly when cross-compiling. A missing icon must
//! never fail the build, so this reports and continues; the Slint compile above still
//! panics on failure, since without it there is no UI at all.
//!
//! The gate is the TARGET OS (`CARGO_CFG_TARGET_OS`), read at run time, not a
//! `#[cfg(windows)]` on this build script: a build script is compiled for and runs on
//! the HOST, so a `cfg(windows)` here was false whenever the Windows binary was
//! cross-compiled from Linux (`scripts/pgo-bolt-build.sh --os windows`), and those
//! binaries silently shipped without any icon (blank titlebar icon, generic Explorer
//! icon). `winresource` itself runs on any host and picks the target's resource
//! compiler (`x86_64-w64-mingw32-windres` for the `gnu` triple) from the `TARGET` it is
//! handed by Cargo.

fn main() {
    slint_build::compile("ui/app.slint").unwrap();

    println!("cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS");
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        embed_icon();
    }
}

/// Embeds `assets/icon.ico` as the executable's Windows icon resource.
///
/// A verbatim twin of `apps/indicatrix-worker/build.rs`'s `embed_icon`: a build script
/// cannot share code across packages without a helper crate both would build first, so
/// an edit to one must be mirrored in the other.
fn embed_icon() {
    println!("cargo:rerun-if-changed=assets/icon.ico");
    let mut res = winresource::WindowsResource::new();
    res.set_icon("assets/icon.ico");
    if let Err(e) = res.compile() {
        println!(
            "cargo:warning=could not embed the application icon ({e}); the binary will build without one"
        );
    }
}
