//! Compiles the Slint UI, and on Windows embeds the application icon.
//!
//! `assets/icon.ico` is generated by `scripts/make-icons.py` (cyan, against
//! `indicatrix-worker`'s emerald). Embedding it as a resource covers both places Windows
//! shows an icon: Explorer's view of the `.exe`, and the window's titlebar/taskbar
//! button -- a Win32 window with no icon of its own falls back to the executable's
//! first icon resource, so no per-window `set_icon` call is needed and no runtime
//! dependency on the file being installed next to the binary.
//!
//! Embedding needs a resource compiler (`rc.exe` for `msvc`, `windres` for `gnu`),
//! neither guaranteed present, particularly when cross-compiling. A missing icon must
//! never fail the build, so this reports and continues; the Slint compile above still
//! panics on failure, since without it there is no UI at all.

fn main() {
    slint_build::compile("ui/app.slint").unwrap();

    #[cfg(windows)]
    embed_icon();
}

#[cfg(windows)]
fn embed_icon() {
    println!("cargo:rerun-if-changed=assets/icon.ico");
    let mut res = winresource::WindowsResource::new();
    res.set_icon("assets/icon.ico");
    if let Err(e) = res.compile() {
        println!(
            "cargo:warning=could not embed the application icon ({e}); the binary will build without one"
        );
    }
}
